In [32]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [33]:
# import numpy
import numpy as np

In [34]:
# convert list to np array
lst = [1,2,3,4]
np.array(lst)

array([1, 2, 3, 4])

In [35]:
# direct array
np.array([3,45,677,8990])

array([   3,   45,  677, 8990])

In [36]:
# 2d array
np.array([[2,3,4],[4,5,6,]])

array([[2, 3, 4],
       [4, 5, 6]])

In [37]:
# eye 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
# combinig Arrays
p = np.ones([3,3],int)
p

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [39]:
# arange(start, stop, step)
z = np.arange(1,60,2).reshape(5,6)

In [40]:
# arthmatic operation

y = np.arange(1,5)
x = np.arange(11,15)
print(x)
print(y)

[11 12 13 14]
[1 2 3 4]


In [41]:
print(x+y) # + 
print(x-y) # -
print(x*y) # *
print(x/y) # /
print(x%y) # %  

[12 14 16 18]
[10 10 10 10]
[11 24 39 56]
[11.          6.          4.33333333  3.5       ]
[0 0 1 2]


In [42]:
print(x**2)

[121 144 169 196]


In [43]:
print(x@y) # dot product
print(np.dot(x,y)) # dot product

130
130


In [44]:
z

array([[ 1,  3,  5,  7,  9, 11],
       [13, 15, 17, 19, 21, 23],
       [25, 27, 29, 31, 33, 35],
       [37, 39, 41, 43, 45, 47],
       [49, 51, 53, 55, 57, 59]])

In [45]:
z.shape

(5, 6)

In [46]:
z.T #tanspose matrix

array([[ 1, 13, 25, 37, 49],
       [ 3, 15, 27, 39, 51],
       [ 5, 17, 29, 41, 53],
       [ 7, 19, 31, 43, 55],
       [ 9, 21, 33, 45, 57],
       [11, 23, 35, 47, 59]])

In [47]:
z.dtype

dtype('int64')

In [48]:
z = z.astype('float64') # astype -> convert data type
z.dtype

dtype('float64')

In [49]:
z

array([[ 1.,  3.,  5.,  7.,  9., 11.],
       [13., 15., 17., 19., 21., 23.],
       [25., 27., 29., 31., 33., 35.],
       [37., 39., 41., 43., 45., 47.],
       [49., 51., 53., 55., 57., 59.]])

In [50]:
# math functions
a = np.array([-4, -3, 5, 6, 6])
print("Sum :",a.sum()) # sum of array
print("Mean :",a.mean()) # mean of array
print("Max :",a.max()) # max of array
print("Min :",a.min()) # min of array
print("Absolute Value :",np.abs(a)) # absolute value


Sum : 10
Mean : 2.0
Max : 6
Min : -4
Absolute Value : [4 3 5 6 6]


In [51]:
# argmax and argmin return the index of max and min value in the array
print("Index of Max :",a.argmax()) # index of max value
print("Index of Min :",a.argmin()) # index of min value

Index of Max : 3
Index of Min : 0


In [52]:
# standard deviation and variance
print("Standard Deviation :",a.std()) # standard deviation
print("Variance :",a.var()) # variance

Standard Deviation : 4.516635916254486
Variance : 20.4


In [53]:
# sum, mean, max, min, std, var , argmax, argmin on the array b
b = np.array([7,3,-2,0,100,25])
print("Sum :",b.sum()) # sum of array
print("Mean :",b.mean()) # mean of array
print("Max :",b.max()) # max of array
print("Min :",b.min()) # min of array
print("Standard Deviation :",b.std()) # standard deviation
print("Variance :",b.var()) # variance
print("Index of Max :",b.argmax()) # index of max value
print("Index of Min :",b.argmin()) # index of min value


Sum : 133
Mean : 22.166666666666668
Max : 100
Min : -2
Standard Deviation : 35.91386299962113
Variance : 1289.8055555555554
Index of Max : 4
Index of Min : 2


In [54]:
s = np.arange(6)**2
s

array([ 0,  1,  4,  9, 16, 25])

In [55]:
# Indexing and slicing
s = np.arange(100)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [56]:
s[0], s[4], s[25], s[99]
# use bracket notation to get the index of the array

(np.int64(0), np.int64(4), np.int64(25), np.int64(99))

In [57]:
# use slicing to get the index of the array
print("first 10 elements:",s[0:10]) # first 10 elements
print("last 10 elements:",s[90:100]) # last 10 elements
print("every other element:",s[::2]) # every other element
print("every other element starting from index 1:",s[1::2]) # every other element starting from index 1
print("reversed array:",s[::-1]) # reverse the array
print("every other element from index 10 to 20:",s[10:20:2]) # every other element from index 10 to 20

first 10 elements: [0 1 2 3 4 5 6 7 8 9]
last 10 elements: [90 91 92 93 94 95 96 97 98 99]
every other element: [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
every other element starting from index 1: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
reversed array: [99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4
  3  2  1  0]
every other element from index 10 to 20: [10 12 14 16 18]


In [58]:
print(s[-5::-2])

[95 93 91 89 87 85 83 81 79 77 75 73 71 69 67 65 63 61 59 57 55 53 51 49
 47 45 43 41 39 37 35 33 31 29 27 25 23 21 19 17 15 13 11  9  7  5  3  1]


In [59]:
print(s[-5:-2])

[95 96 97]


In [60]:
r = s.reshape((10,10))
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [61]:
r[3,4] # get the element at row 3 and column 4

np.int64(34)

In [62]:
r[2,1]

np.int64(21)