In [27]:
import numpy as np

In [28]:
"""
1. # Create a constant array
# Prints "[[ 7. 7.]
             [ 7. 7.]]"
"""

np.ones((2, 2)) * 7

array([[7., 7.],
       [7., 7.]])

In [29]:
"""
2. # Create an array filled with random values
# Might print "[[ 0.91940167 0.08143941]
 [ 0.68744134 0.87236687]]"
"""
np.random.random((2, 2))

array([[0.54531454, 0.88964917],
       [0.6922898 , 0.3751075 ]])

In [30]:
"""
3. Create a NumPy array containing the numbers from 10 to 50.
 Display:
The array
Number of elements
Shape
Dimension
Data type
"""

x = np.arange(10, 51)
print("The array:", x)
print("Number of elements:", x.size)
print("Shape:", x.shape)
print("Dimension:", x.ndim)
print("Data type:", x.dtype)



The array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
Number of elements: 41
Shape: (41,)
Dimension: 1
Data type: int64


In [31]:
""" 
4. Using NumPy, create:
A 1D array containing 10 zeros
A 3 × 3 array containing ones
A 4 × 4 identity matrix
An array containing numbers from 5 to 50 with a step size of 5.
"""


a = np.zeros(10)
print("1D array containing 10 zeros:\n", a)
b = np.ones((3, 3)) 
print("3 × 3 array containing ones:\n", b)
c = np.identity(4)
print("4 × 4 identity matrix:\n", c)
d = np.arange(5, 51, 5)
print("Array containing numbers from 5 to 50 with a step size of 5:\n", d)

1D array containing 10 zeros:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
3 × 3 array containing ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
4 × 4 identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Array containing numbers from 5 to 50 with a step size of 5:
 [ 5 10 15 20 25 30 35 40 45 50]


In [32]:
""" 
5. Create an array containing numbers from 1 to 24. Reshape it into:
4 × 6
6 × 4
2 × 3 × 4
Display the shape and ndim of each result.
"""

s = np.arange(1, 25)
s1 = s.reshape(4, 6)
print("4 × 6 array:\n", s1)
print("Shape:", s1.shape)
print("Number of dimensions:", s1.ndim)

s2 = s.reshape(6, 4)
print("\n6 × 4 array:\n", s2)
print("Shape:", s2.shape)
print("Number of dimensions:", s2.ndim)

s3 = s.reshape(2, 3, 4)
print("\n2 × 3 × 4 array:\n", s3)
print("Shape:", s3.shape)
print("Number of dimensions:", s3.ndim)

4 × 6 array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6)
Number of dimensions: 2

6 × 4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Shape: (6, 4)
Number of dimensions: 2

2 × 3 × 4 array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
Shape: (2, 3, 4)
Number of dimensions: 3


In [33]:
""" 
6. Consider: marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])
Write NumPy statements to display:
First element
Last element
Third element
First four elements
Last three elements
"""
marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])
print("First element:", marks[0])
print("Last element:", marks[-1])  
print("Third element:", marks[2])
print("First four elements:", marks[:4])
print("Last three elements:", marks[-3:])

First element: 78
Last element: 81
Third element: 92
First four elements: [78 85 92 67]
Last three elements: [73 95 81]


In [34]:
""" 
7. Create:
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])
Calculate:
a + b
a - b
a * b
a / b
Square of every element in a 
"""
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])
print("a + b:", a + b)  
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)
print("Square of every element in a:", a ** 2)

a + b: [15 30 45 60 75]
a - b: [ 5 10 15 20 25]
a * b: [  50  200  450  800 1250]
a / b: [2. 2. 2. 2. 2.]
Square of every element in a: [ 100  400  900 1600 2500]


In [35]:
""" 
8. Given: 
salary = np.array([25000, 32000, 28000, 45000, 
                   50000, 38000, 42000, 30000]) 
 
Find: 
 
Total salary 
Average salary 
Highest salary 
Lowest salary 
Median salary 
Standard deviation 
"""
salary = np.array([25000, 32000, 28000, 45000, 50000, 38000, 42000, 30000])
print("Total salary:", salary.sum())
print("Average salary:", salary.mean())
print("Highest salary:", salary.max())  
print("Lowest salary:", salary.min())
print("Median salary:", np.median(salary))
print("Standard deviation:", salary.std())

Total salary: 290000
Average salary: 36250.0
Highest salary: 50000
Lowest salary: 25000
Median salary: 35000.0
Standard deviation: 8317.902379807063


In [36]:
""" 
9. Given: marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84]) 
 
Using NumPy boolean indexing, find: 
 
Marks greater than 75 
Marks between 50 and 80 
Number of students who scored below 50 
Percentage of students who scored 60 or above 
 
Do not use a Python for loop. 
"""
marks = np.array([45, 78, 89, 32, 67, 90, 55, 76, 41, 84])
print("Marks greater than 75:", marks[marks > 75])
print("Marks between 50 and 80:", marks[(marks >= 50) & (marks <= 80)])
print("Number of students who scored below 50:", np.sum(marks < 50))
print("Percentage of students who scored 60 or above:", (np.sum(marks >= 60) / len(marks)) * 100)

Marks greater than 75: [78 89 90 76 84]
Marks between 50 and 80: [78 67 55 76]
Number of students who scored below 50: 3
Percentage of students who scored 60 or above: 60.0


In [37]:
""" 
10. The following array contains marks of four students in three 
subjects: 
 
marks = np.array([ 
    [80, 75, 90], 
    [65, 70, 72], 
    [88, 92, 85], 
    [55, 60, 58] 
]) 
 
Calculate: 
 
Total marks of each student 
Average marks of each student 
Average marks in each subject 
Student with the highest total 
Highest mark in each subject. 
"""
marks = np.array([
    [80, 75, 90],
    [65, 70, 72],
    [88, 92, 85],
    [55, 60, 58]
])
print("Total marks of each student:", marks.sum(axis=1))
print("Average marks of each student:", marks.mean(axis=1))
print("Average marks in each subject:", marks.mean(axis=0))
print("Student with the highest total:", np.argmax(marks.sum(axis=1)))
print("Highest mark in each subject:", marks.max(axis=0))

Total marks of each student: [245 207 265 173]
Average marks of each student: [81.66666667 69.         88.33333333 57.66666667]
Average marks in each subject: [72.   74.25 76.25]
Student with the highest total: 2
Highest mark in each subject: [88 92 90]


In [38]:
""" 
11. Create: 
 
A = np.array([ 
    [1, 2], 
    [3, 4] 
]) 
 
B = np.array([ 
    [5, 6], 
    [7, 8]
    ]) 
 
Perform: 
 
Matrix addition 
Element-wise multiplication 
Matrix multiplication 
Transpose of A. 
 
explain the difference between: 
A * B and A @ B 
 
"""

A = np.array([
    [1, 2], 
    [3, 4] ])

B = np.array([
    [5, 6], 
    [7, 8]
])  

print("Matrix addition:\n", A + B)
print("Element-wise multiplication:\n", A * B)
print("Matrix multiplication:\n", A @ B)
print("Transpose of A:\n", A.T)
print()

print("A*B is element-wise multiplication, where each element of A is multiplied by the corresponding element of B. \nWhereas A@B is matrix multiplication, which involves taking the dot product of rows of A with columns of B.")

Matrix addition:
 [[ 6  8]
 [10 12]]
Element-wise multiplication:
 [[ 5 12]
 [21 32]]
Matrix multiplication:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]

A*B is element-wise multiplication, where each element of A is multiplied by the corresponding element of B. 
Whereas A@B is matrix multiplication, which involves taking the dot product of rows of A with columns of B.


In [39]:
""" 
12. Daily temperatures for two weeks are: 
 
temperature = np.array([ 
    31, 32, 33, 35, 36, 34, 32, 
    30, 29, 31, 33, 35, 37, 36 
]) 
 
Find: 
 
Mean temperature 
Maximum and minimum temperatures 
Number of days above the average temperature 
Temperatures greater than 34°C 
Difference between maximum and minimum 
Standard deviation 
 
"""

temperature = np.array([
    31, 32, 33, 35, 36, 34, 32,
    30, 29, 31, 33, 35, 37, 36
])

print("Mean temperature:", temperature.mean())
print("Maximum temperature:", temperature.max())
print("Minimum temperature:", temperature.min())
print("Number of days above average:", np.sum(temperature > temperature.mean()))
print("Temperatures greater than 34°C:", temperature[temperature > 34])
print("Difference between maximum and minimum:", temperature.max() - temperature.min())
print("Standard deviation:", temperature.std())

Mean temperature: 33.142857142857146
Maximum temperature: 37
Minimum temperature: 29
Number of days above average: 6
Temperatures greater than 34°C: [35 36 35 37 36]
Difference between maximum and minimum: 8
Standard deviation: 2.356060357495806


In [40]:
""" 
13. Monthly sales of a company are: 
sales = np.array([ 
    12000, 15000, 17000, 14000, 
    18000, 21000, 19000, 22000, 
    25000, 23000, 26000, 28000 
]) 
 
Determine: 
 
Total annual sales 
Average monthly sales 
Month with the highest sales 
Month with the lowest sales 
Number of months with sales above ₹20,000 
Percentage increase from January to December 
 
Hint: Remember that NumPy indexing starts at 0, while month numbering 
normally starts at 1.
"""

sales = np.array([
    12000, 15000, 17000, 14000,
    18000, 21000, 19000, 22000,
    25000, 23000, 26000, 28000
])

print("Total annual sales:", sales.sum())
print("Average monthly sales:", sales.mean())   
print("Month with the highest sales:", np.argmax(sales) + 1)
print("Month with the lowest sales:", np.argmin(sales) + 1)
print("Number of months with sales above ₹20,000:", np.sum(sales > 20000))
print("Percentage increase from January to December:", (sales[-1] - sales[0]) / sales[0] * 100)

Total annual sales: 240000
Average monthly sales: 20000.0
Month with the highest sales: 12
Month with the lowest sales: 1
Number of months with sales above ₹20,000: 6
Percentage increase from January to December: 133.33333333333331


In [41]:
""" 
14. Consider marks of five students in four subjects: 
 
marks = np.array([ 
    [78, 85, 90, 88], 
    [65, 70, 72, 68], 
    [92, 88, 95, 91], 
    [55, 60, 58, 62], 
    [80, 75, 82, 79] 
]) 
 
Write a NumPy program that calculates: 
 
Total marks of every student 
Average of every student 
Average mark for every subject 
Highest-scoring student 
Lowest-scoring student 
Students whose average is greater than 80 
Overall class average 
 
Then assign a performance category based on average: 
 
|  Average | Category          | 
| -------: | ----------------- | 
|     ≥ 85 | Excellent         | 
| 70–84.99 | Good              | 
| 50–69.99 | Average           | 
|     < 50 | Needs Improvement | 
 
Challenge: Try assigning these categories using np.where() or np.select() 
instead of a Python loop.
"""
marks = np.array([
    [78, 85, 90, 88],
    [65, 70, 72, 68],
    [92, 88, 95, 91],
    [55, 60, 58, 62],
    [80, 75, 82, 79]
])  
print("Total marks of every student:", marks.sum(axis=1))
print("Average of every student:", marks.mean(axis=1))  
print("Average mark for every subject:", marks.mean(axis=0))
highest_scoring_student = np.argmax(marks.sum(axis=1))
lowest_scoring_student = np.argmin(marks.sum(axis=1))
print("Highest-scoring student:", highest_scoring_student + 1)
print("Lowest-scoring student:", lowest_scoring_student + 1)
print("Students whose average is greater than 80:", np.where(marks.mean(axis=1) > 80)[0] + 1)
print("Overall class average:", marks.mean())

scores = marks.mean(axis=1)
conditions = [scores >= 85, (scores >= 70) & (scores < 85), (scores >= 50) & (scores < 70)]
categories = ['Excellent', 'Good', 'Average']

performance_categories = np.select(conditions, categories, default='Needs Improvement')
print("Performance categories:\n", performance_categories)


Total marks of every student: [341 275 366 235 316]
Average of every student: [85.25 68.75 91.5  58.75 79.  ]
Average mark for every subject: [74.  75.6 79.4 77.6]
Highest-scoring student: 3
Lowest-scoring student: 4
Students whose average is greater than 80: [1 3]
Overall class average: 76.65
Performance categories:
 ['Excellent' 'Average' 'Excellent' 'Average' 'Good']


In [42]:
""" 
15. Generate 20 random integers between 1 and 100. 
"""
p = np.random.randint(1, 101, size=20)
p

array([ 2, 80, 85, 50, 56, 77,  2,  9, 72, 19, 75, 41, 73, 65, 48, 88, 88,
        6, 64, 31], dtype=int32)

In [43]:
""" 
16. Find all even numbers from the generated array. 
"""
p[p % 2 == 0]

array([ 2, 80, 50, 56,  2, 72, 48, 88, 88,  6, 64], dtype=int32)

In [44]:
""" 
17. Replace values below 50 with 0.
"""


p[p < 50] = 0
p

array([ 0, 80, 85, 50, 56, 77,  0,  0, 72,  0, 75,  0, 73, 65,  0, 88, 88,
        0, 64,  0], dtype=int32)

In [45]:
""" 
18. Sort the array in ascending and descending order. 
"""


p_sorted_asc = np.sort(p)
p_sorted_desc = np.sort(p)[::-1]
print("Array sorted in ascending order:", p_sorted_asc)
print("Array sorted in descending order:", p_sorted_desc)

Array sorted in ascending order: [ 0  0  0  0  0  0  0  0 50 56 64 65 72 73 75 77 80 85 88 88]
Array sorted in descending order: [88 88 85 80 77 75 73 72 65 64 56 50  0  0  0  0  0  0  0  0]


In [46]:
""" 
19. Find unique values and their frequencies. 
"""
unique_values, frequencies = np.unique(p, return_counts=True)
print("Unique values:", unique_values)

Unique values: [ 0 50 56 64 65 72 73 75 77 80 85 88]


In [47]:
""" 
20. Create a 5 × 5 random matrix and calculate row-wise and column-wise 
means. 
"""
matrix = np.random.randint(1, 101, size=(5, 5))
print("Random 5 × 5 matrix:\n", matrix)
row_means = np.mean(matrix, axis=1)
column_means = np.mean(matrix, axis=0)
print("Row-wise means:", row_means)
print("Column-wise means:", column_means)

Random 5 × 5 matrix:
 [[ 9 84 45 58 25]
 [91 46 22 14 50]
 [ 6 57 24 51 68]
 [74 48 53 60 74]
 [ 1 42 38 86 37]]
Row-wise means: [44.2 44.6 41.2 61.8 40.8]
Column-wise means: [36.2 55.4 36.4 53.8 50.8]


In [48]:
""" 
21. Take your own example to normalize an array.  
"""

def normal(arr):
    normalized_arr = (arr - np.min(arr)) / (np.max(arr) - np.min(arr))
    return normalized_arr

x= np.array([10, 34,51,66,4,67])
normal(x)

array([0.0952381 , 0.47619048, 0.74603175, 0.98412698, 0.        ,
       1.        ])

In [49]:
""" 
22. use your own data to standardize an array. 
"""


def standardize(arr):
    standardized_arr = (arr - np.mean(arr)) / np.std(arr)
    return standardized_arr

x = np.array([10, 34, 51, 66, 4, 67])
standardize(x)

array([-1.14707459, -0.18673307,  0.49350883,  1.09372228, -1.38715997,
        1.13373651])

In [50]:
""" 
23. Create a NumPy array containing 100 random exam marks and determine 
how many students fall into the ranges 0–39, 40–59, 60–79, and 80–100. 
"""
exam_marks = np.random.randint(0, 101, size=100)
print("Random exam marks:\n", exam_marks)

# Count students in each range
count_0_39 = np.sum((exam_marks >= 0) & (exam_marks <= 39))
count_40_59 = np.sum((exam_marks >= 40) & (exam_marks <= 59))
count_60_79 = np.sum((exam_marks >= 60) & (exam_marks <= 79))
count_80_100 = np.sum((exam_marks >= 80) & (exam_marks <= 100))

print("Number of students in range 0–39:", count_0_39)
print("Number of students in range 40–59:", count_40_59)
print("Number of students in range 60–79:", count_60_79)
print("Number of students in range 80–100:", count_80_100)

Random exam marks:
 [ 38  39   5  12  45   5  77  39  38  15  80  47  59  93  17  25  68  84
  78  35  89  30  44  10  44  51  61  28  44  95  99  29  37  64  24  22
   1  86  72  72   0   0  58  60  44  56  76  70  58  53  36  45  88  21
  67   6  72   7  51  74  33   6  91  92  18  32  68  60 100  46  48  61
  60  58  33  80  83  57  76  81  96  74  33  26  95   1  20  64  36  66
  60  38  84  72  10  46  55  29  56  58]
Number of students in range 0–39: 38
Number of students in range 40–59: 22
Number of students in range 60–79: 23
Number of students in range 80–100: 17


In [51]:
import time

In [52]:
""" 
24. Compare the time required to multiply 1,000,000 numbers using a 
Python list and a NumPy array.
"""


# Create a Python list and a NumPy array with 1,000,000 numbers
python_list = list(range(1, 1000001))
numpy_array = np.arange(1, 1000001)

# Measure time for Python list multiplication
start_time = time.time()
result_list = [x * 2 for x in python_list]
end_time = time.time()
time_list = end_time - start_time

# Measure time for NumPy array multiplication
start_time = time.time()
result_array = numpy_array * 2
end_time = time.time()
time_array = end_time - start_time

print("Time required for Python list multiplication:", time_list)
print("Time required for NumPy array multiplication:", time_array)
print("Numpy is aproximately {:.2f} times faster than Python list.".format(time_list / time_array))

Time required for Python list multiplication: 0.14111757278442383
Time required for NumPy array multiplication: 0.004601240158081055
Numpy is aproximately 30.67 times faster than Python list.
